name: portfolio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.3.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter:
  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/sf-ui-text/SFUIText-Bold.ttf
        - asset: assets/fonts/sf-ui-text/SFUIText-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/sf-ui-text/SFUIText-Heavy.ttf
        - asset: assets/fonts/sf-ui-text/SFUIText-HeavyItalic.ttf
          style: italic
        - asset: assets/fonts/sf-ui-text/SFUIText-Light.ttf
        - asset: assets/fonts/sf-ui-text/SFUIText-LightItalic.ttf
          style: italic
        - asset: assets/fonts/sf-ui-text/SFUIText-Medium.ttf
        - asset: assets/fonts/sf-ui-text/SFUIText-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/sf-ui-text/SFUIText-Regular.ttf
        - asset: assets/fonts/sf-ui-text/SFUIText-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/sf-ui-text/SFUIText-Semibold.ttf
        - asset: assets/fonts/sf-ui-text/SFUIText-SemiboldItalic.ttf
          style: italic
