name: portfolio
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  enefty_icons: 1.0.7
  url_launcher: 6.2.6
  flutter_svg: 2.0.10+1
  either_dart: 1.0.0
  skeletonizer: 1.1.2+1
  flutter_modular: 5.0.3
  url_strategy: 0.2.0
  dio: 5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.3
  flutter_lints: 3.0.0
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-black-italic.otf
        - asset: assets/fonts/sf-pro-display/sf-pro-display-bold.otf
        - asset: assets/fonts/sf-pro-display/sf-pro-display-heavy-italic.otf
          style: italic
        - asset: assets/fonts/sf-pro-display/sf-pro-display-light-italic.otf
          style: italic
        - asset: assets/fonts/sf-pro-display/sf-pro-display-medium.otf
        - asset: assets/fonts/sf-pro-display/sf-pro-display-regular.otf
        - asset: assets/fonts/sf-pro-display/sf-pro-display-semi-bold-italic.otf
          style: italic
        - asset: assets/fonts/sf-pro-display/sf-pro-display-thin-italic.otf
          style: italic
        - asset: assets/fonts/sf-pro-display/sf-pro-display-ultra-light-italic.otf
          style: italic
